// const books = [
// 	{
// 		title: 'The Pragmatic Programmer: From Journeyman to Master',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://imagery.pragprog.com/products/59/tpp.jpg?1339433898',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'business'
// 	},
// 	{
// 		title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
// 		author: [ 'Robert C. Martin' ],
// 		format: 'Paperback',
// 		pubDate: 'August 11th 2000',
// 		publisher: 'Prentice Hall',
// 		isbn: '0132350882',
// 		bookCover:
// 			'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1436202607l/3735293._SX318_.jpg',
// 		rating: 4.4,
// 		numOfRatings: 13557,
// 		numOfReviews: 809,
// 		isAvailable: true,
// 		category: 'business'
// 	},
// 	{
// 		title: 'Code Complete',
// 		author: [ 'Steve McConnell' ],
// 		format: 'Paperback',
// 		pubDate: 'June 19th 2004',
// 		publisher: 'Microsoft Press',
// 		isbn: '0735619670',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1396837641l/4845.jpg',
// 		rating: 4.29,
// 		numOfRatings: 8075,
// 		numOfReviews: 376,
// 		isAvailable: false,
// 		category: 'business'
// 	},
// 	{
// 		title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
// 		author: [
// 			'Erich Gamma',
// 			'Ralph Johnson',
// 			'John Vlissides',
// 			'Richard Helm',
// 			'Random name for testing purposes'
// 		],
// 		format: 'Hardcover',
// 		pubDate: 'November 10th 1994',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '0201633612',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348027904l/85009.jpg',
// 		rating: 4.18,
// 		numOfRatings: 9432,
// 		numOfReviews: 328,
// 		isAvailable: true,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'The Clean Coder: A Code of Conduct for Professional Programmers',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347470803l/10284614.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: false,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'Refactoring: Improving the Design of Existing Code',
// 		author: [ 'Martin Fowler', 'Kent Beck', 'Don Roberts', 'Erich Gamma' ],
// 		format: 'Hardcover',
// 		pubDate: 'July 8th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '0201485672',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1386925632l/44936.jpg',
// 		rating: 4.24,
// 		numOfRatings: 6609,
// 		numOfReviews: 258,
// 		isAvailable: true,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'The Mythical Man-Month: Essays on Software Engineering',
// 		author: [ 'Frederick P. Brooks Jr.' ],
// 		format: 'Paperback',
// 		pubDate: 'August 12th 1995',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '0201835959',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348430512l/13629.jpg',
// 		rating: 4.04,
// 		numOfRatings: 12349,
// 		numOfReviews: 561,
// 		isAvailable: true,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'Structure and Interpretation of Computer Programs (MIT Electrical Engineering and Computer Science)',
// 		author: [ 'Harold Abelson', 'Gerald Jay Sussman', 'Julie Sussman' ],
// 		format: 'Paperback',
// 		pubDate: 'July 25th 1996',
// 		publisher: 'MIT Press',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391032527l/43713.jpg',
// 		rating: 4.11,
// 		numOfRatings: 9653,
// 		numOfReviews: 536,
// 		isAvailable: false,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'JavaScript: The Good Parts',
// 		author: [ 'Douglas Crockford' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328834793l/2998152.jpg',
// 		rating: 4.01,
// 		numOfRatings: 6043,
// 		numOfReviews: 531,
// 		isAvailable: true,
// 		category: 'computer science'
// 	},
// 	{
// 		title: 'The C Programming Language',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391032531l/515601.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'data science'
// 	},
// 	{
// 		title: 'Head First Design Patterns',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1408309444l/58128.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'data science'
// 	},
// 	{
// 		title: 'Introduction to Algorithms',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387741681l/108986.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'data science'
// 	},
// 	{
// 		title: 'Working Effectively with Legacy Code',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348627451l/44919.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'design'
// 	},
// 	{
// 		title: 'Effective Java Programming Language Guide',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1433511045l/105099.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'design'
// 	},
// 	{
// 		title: 'Programming Pearls',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1385191091l/52084.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'design'
// 	},
// 	{
// 		title: 'Domain-Driven Design: Tackling Complexity in the Heart of Software',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1287493789l/179133.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'design'
// 	},
// 	{
// 		title: 'Code',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328830222l/44882.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'development'
// 	},
// 	{
// 		title: 'Test Driven Development: By Example',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1372039943l/387190.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'development'
// 	},
// 	{
// 		title: 'Patterns of Enterprise Application Architecture',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover:
// 			'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1440294142l/70156._SX318_.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'productivity'
// 	},
// 	{
// 		title: 'Coders at Work: Reflections on the Craft of Programming',
// 		author: [ 'Andy Hunt', 'Dave Thomas' ],
// 		format: 'Paperback',
// 		pubDate: 'October 30th 1999',
// 		publisher: 'Addison-Wesley Professional',
// 		isbn: '020161622X',
// 		bookCover: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1349026758l/6713575.jpg',
// 		rating: 4.31,
// 		numOfRatings: 14469,
// 		numOfReviews: 796,
// 		isAvailable: true,
// 		category: 'productivity'
// 	}
// ];

// export default books;
